### ISSUE TITLE
Have GPDAG use the same bitset convention as the rest of the code

### ISSUE THREAD

**Issue by matsen** [phylovi/libsbn#247]
Right now it uses a different "full subsplit" convention.

**Comment by matsen** [comment]
Also remove duplication from `classic_indexer_`.

**Comment by matsen** [comment]
So, here's an example rooted indexer. Note that the vertical bars are just to make things easy for us to read.

      "00111",              // ((x0,x1),(x2,(x3,x4)))
      "01111",              // (x0,(((x1,x3),x2),x4)) and ((x1,((x2,x4),x3)),x0)
      "00010",              // (x3,((x0,(x4,x1)),x2))
      "00100|01010|00010",  // ((x1,x3),x2)
      "00111|11000|01000",  // ((x0,x1),(x2,(x3,x4)))
      "00100|00011|00001",  // (x2,(x3,x4))
      "11000|00111|00011",  // ((x0,x1),(x2,(x3,x4)))
      "00100|11001|01001",  // ((x0,(x4,x1)),x2)
      "10000|01001|00001",  // (x0,(x4,x1))
      "01000|00111|00010",  // (x1,((x2,x4),x3))
      "10000|01111|00001",  // (x0,(((x1,x3),x2),x4))
      "10000|01111|00111",  // ((x1,((x2,x4),x3)),x0)
      "00010|00101|00001",  // ((x2,x4),x3)
      "00001|01110|00100",  // (((x1,x3),x2),x4)
      "00010|11101|00100"   // (x3,((x0,(x4,x1)),x2))

Let's think about how we could fit trivial subsplits into this framework.
Say we are interested in the leaves below this:

      "10000|01001|00001",  // (x0,(x4,x1))

Could we use

      "00000|10000|00000",  // x0
      "00000|01000|00000",  // x1
      "00000|00001|00000",  // x4

? Perhaps this is ambiguous but I can't see how right now.

**Comment by matsen** [comment]
Emerging convention with @mdkarcher --

If the third field is all zeroes, then this is a trivial subsplit. Generalizing what we have above, 

    01000|00110|00000

would express a non-splitting subsplit.

He goes further and expresses rootsplits as PCSPs like

    00000|11111|00111

which is a great idea. We could consider this as a future issue.

But it would seem more parsimonious with his work to use

  "10000|00000|00000",  // x0
  "01000|00000|00000",  // x1
  "00001|00000|00000",  // x4

for our notion of trivial subsplits.

**Comment by mdkarcher** [comment]
To comment on the final point, which I'm reading as "how to handle singleton clades/tips as bit arrays", I think I'd need to know more about your use case. By analogy, I picked shaping my root splits as PCSPs in the above manner to minimize special-casing, because it is handy to include the root splits (as children) in a traversal of all PCSPs.

I guess my question comes down to, in what cases would you like to refer to a singleton clade/tip as a PCSP? I think that would illustrate whether you want to have the singleton be the child of the PCSP (with the parent censored) or as the parent of the PCSP (with no children). If you want to refer to a tip, would there be a lot of special casing to have a single-width bit array like "01000"?

**Comment by matsen** [comment]
Thanks for thinking on this @mdkarcher !

We want to assign branch lengths to "pendant" branches, thus we need some way to index them.

It's funny, though, now that I'm thinking about this it would seem to agree better with the rest of the scheme to use a setup like

  01000|00001|00000

to express the pendant branch length for `x1` in `(x4,x1)`

@junseonghwan, do you see a problem with that? 

We could do a single-width bitarray, though my general sense is that it's nice to move away from these sorts of special cases. Indeed, with that in mind it seems better to just use `00000|...` for rootsplits. 

Looking forward for further thoughts.

**Comment by matsen** [comment]
Closed by https://github.com/phylovi/libsbn/commit/4f1041984f6434171aae7be657dfe5112bc8d964
